server:
  port: 8080

spring:
  application:
    name: blog-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: blog-content
          uri: http://localhost:8081
          predicates:
            - Path=/api/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
