server:
  port: ${PORT:${SERVER_PORT:8081}}

spring:
  application:
    name: blog-service-content
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:myblog}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never

springdoc:
  swagger-ui:
    path: /swagger-ui.html

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:info}
    com.zzq.blog: ${LOGGING_LEVEL_APP:info}
    com.zaxxer.hikari: ${LOGGING_LEVEL_HIKARI:info}

management:
  endpoints:
    web:
      exposure:
        include: health,info
