server:
  port: 8081

spring:
  application:
    name: blog-service-content
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:myblog}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never

springdoc:
  swagger-ui:
    path: /swagger-ui.html

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.zzq.blog.content: info
