ALTER TABLE user_profile COMMENT = '站点个人资料表';

ALTER TABLE user_profile
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN name VARCHAR(64) NOT NULL COMMENT '姓名',
    MODIFY COLUMN title VARCHAR(128) NOT NULL COMMENT '个人标题/身份描述',
    MODIFY COLUMN university VARCHAR(128) NOT NULL COMMENT '毕业院校',
    MODIFY COLUMN major VARCHAR(128) NOT NULL COMMENT '专业名称',
    MODIFY COLUMN location VARCHAR(64) COMMENT '所在地区',
    MODIFY COLUMN email VARCHAR(128) COMMENT '联系邮箱',
    MODIFY COLUMN bio VARCHAR(255) COMMENT '个人简介',
    MODIFY COLUMN focus_areas VARCHAR(255) COMMENT '关注方向，逗号分隔',
    MODIFY COLUMN highlights VARCHAR(255) COMMENT '亮点信息，逗号分隔';

ALTER TABLE category COMMENT = '文章分类表';

ALTER TABLE category
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN name VARCHAR(64) NOT NULL COMMENT '分类名称';

ALTER TABLE tag COMMENT = '文章标签表';

ALTER TABLE tag
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN name VARCHAR(64) NOT NULL COMMENT '标签名称';

ALTER TABLE article COMMENT = '文章内容表';

ALTER TABLE article
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN title VARCHAR(128) NOT NULL COMMENT '文章标题',
    MODIFY COLUMN summary VARCHAR(255) NOT NULL COMMENT '文章摘要',
    MODIFY COLUMN content_markdown TEXT NOT NULL COMMENT 'Markdown 正文内容',
    MODIFY COLUMN cover_image VARCHAR(255) COMMENT '封面图地址',
    MODIFY COLUMN category_id BIGINT NOT NULL COMMENT '所属分类ID',
    MODIFY COLUMN publish_date DATE NOT NULL COMMENT '发布日期',
    MODIFY COLUMN reading_time INT DEFAULT 5 COMMENT '预计阅读时长，单位分钟',
    MODIFY COLUMN status TINYINT DEFAULT 1 COMMENT '文章状态，1-已发布';

ALTER TABLE article_tag COMMENT = '文章与标签关联表';

ALTER TABLE article_tag
    MODIFY COLUMN article_id BIGINT NOT NULL COMMENT '文章ID',
    MODIFY COLUMN tag_id BIGINT NOT NULL COMMENT '标签ID';

ALTER TABLE site_module COMMENT = '站点模块配置表';

ALTER TABLE site_module
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN page VARCHAR(32) NOT NULL COMMENT '所属页面标识，如 home/about/global',
    MODIFY COLUMN module_key VARCHAR(64) NOT NULL COMMENT '模块唯一键',
    MODIFY COLUMN title VARCHAR(128) NOT NULL COMMENT '模块标题',
    MODIFY COLUMN module_type VARCHAR(32) NOT NULL COMMENT '模块类型',
    MODIFY COLUMN enabled TINYINT DEFAULT 1 COMMENT '是否启用，1-启用，0-停用',
    MODIFY COLUMN sort_order INT DEFAULT 0 COMMENT '排序值，越小越靠前',
    MODIFY COLUMN payload_json TEXT COMMENT '模块负载JSON配置';
